import { Badge } from '@/types/gamification';

export const ALL_CIVIC_BADGES: Badge[] = [
  {
    id: 'first_spot',
    title: 'First Spot',
    description: 'Submitted your first verified roadway hazard observation with photo evidence.',
    icon: 'first_spot',
    category: 'reporting',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Novice Scout',
  },
  {
    id: 'road_scout',
    title: 'Road Scout',
    description: 'Identified and logged 3+ road hazards to protect fellow citizens.',
    icon: 'road_scout',
    category: 'reporting',
    requiredCount: 3,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'District Scout',
  },
  {
    id: 'community_sentinel',
    title: 'Community Sentinel',
    description: 'Logged 8+ verified hazard reports across your city.',
    icon: 'community_sentinel',
    category: 'reporting',
    requiredCount: 8,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Road Sentinel',
  },
  {
    id: 'hazard_hunter',
    title: 'Master Scout',
    description: 'Elite road guardian with 15+ comprehensive verified hazard submissions.',
    icon: 'hazard_hunter',
    category: 'reporting',
    requiredCount: 15,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Master Scout',
  },
  {
    id: 'first_verifier',
    title: 'On-Site Verifier',
    description: 'Confirmed your first active hazard on-site to assist community safety.',
    icon: 'first_verifier',
    category: 'verification',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Field Verifier',
  },
  {
    id: 'civic_guardian',
    title: 'Civic Guardian',
    description: 'Verified and validated 10+ community hazard reports in your area.',
    icon: 'civic_guardian',
    category: 'verification',
    requiredCount: 10,
    currentCount: 0,
    isUnlocked: false,
    tier: 'silver',
    rewardTitle: 'Civic Guardian',
  },
  {
    id: 'road_restorer',
    title: 'First Restoration',
    description: 'Captured and uploaded live photo proof of a repaired road hazard.',
    icon: 'road_restorer',
    category: 'resolution',
    requiredCount: 1,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'Road Restorer',
  },
  {
    id: 'fixer_champion',
    title: 'Fixer Champion',
    description: 'Confirmed 3+ road repairs with photographic resolution proof.',
    icon: 'fixer_champion',
    category: 'resolution',
    requiredCount: 3,
    currentCount: 0,
    isUnlocked: false,
    tier: 'gold',
    rewardTitle: 'Fixer Champion',
  },
  {
    id: 'ai_visionary',
    title: 'AI Visionary',
    description: 'Utilized Gemini AI Vision to classify and report 3+ road issues.',
    icon: 'ai_visionary',
    category: 'reporting',
    requiredCount: 3,
    currentCount: 0,
    isUnlocked: false,
    tier: 'bronze',
    rewardTitle: 'AI Visionary',
  },
  {
    id: 'streak_master',
    title: '7-Day Streaker',
    description: 'Maintained an active reporting and verification streak for 7 consecutive days.',
    icon: 'streak_master',
    category: 'streak',
    requiredCount: 7,
    currentCount: 0,
    isUnlocked: false,
    tier: 'platinum',
    rewardTitle: 'Streak Champion',
  },
];
